name: CI/CD Pipeline with Cypress

on:
  pull_request:
    branches:
      - feature
      - develop
  
jobs:
  test:
    # Operating system to run job on
    name: cypress-test
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install
        name: Run Cypress
        uses: Cypress-io/github-action@v6
      # Run build
        with: 
          build: npm run build

      # Run tests
      
          start: npm run start
          component: true
